name: Laravel CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: laravel
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, dom, fileinfo, mysql, gd, zip
        coverage: xdebug

    - uses: actions/checkout@v3

    - name: Get Composer Cache Directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install Dependencies
      run: composer install --prefer-dist --no-interaction --no-progress
      env:
        COMPOSER_PROCESS_TIMEOUT: 0
        COMPOSER_NO_INTERACTION: 1
        COMPOSER_NO_AUDIT: 1

    - name: Create .env file
      run: |
        cat > .env << 'EOF'
        APP_NAME="Sistem Informasi Penjualan Pupuk"
        APP_ENV=testing
        APP_KEY=
        APP_DEBUG=true
        APP_URL=http://localhost

        # Locale & Timezone
        APP_LOCALE=id
        APP_FALLBACK_LOCALE=id
        APP_TIMEZONE=Asia/Jakarta

        # Database Configuration
        DB_CONNECTION=mysql
        DB_HOST=127.0.0.1
        DB_PORT=3306
        DB_DATABASE=laravel
        DB_USERNAME=root
        DB_PASSWORD=password

        # Cache & Session
        CACHE_DRIVER=array
        SESSION_DRIVER=array
        SESSION_LIFETIME=120

        # Queue (for background processing)
        QUEUE_CONNECTION=sync

        # Mail Configuration
        MAIL_MAILER=array

        # File Storage
        FILESYSTEM_DISK=local

        # Logging
        LOG_CHANNEL=stderr
        LOG_DEPRECATIONS_CHANNEL=null
        LOG_LEVEL=debug

        # Media Library
        MEDIA_DISK=public
        EOF
      env:
        COMPOSER_PROCESS_TIMEOUT: 0
        COMPOSER_NO_INTERACTION: 1
        COMPOSER_NO_AUDIT: 1

    - name: Generate key
      run: php artisan key:generate --force
      env:
        COMPOSER_PROCESS_TIMEOUT: 0
        COMPOSER_NO_INTERACTION: 1
        COMPOSER_NO_AUDIT: 1
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: laravel
        DB_USERNAME: root
        DB_PASSWORD: password

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Create Database Schema
      run: |
        # Nonaktifkan pengecekan foreign key sementara
        mysql -h127.0.0.1 -uroot -ppassword -e "SET GLOBAL FOREIGN_KEY_CHECKS=0;"
        
        # Jalankan migrasi tanpa pengecekan foreign key
        php artisan migrate --force --no-interaction
        
        # Aktifkan kembali pengecekan foreign key
        mysql -h127.0.0.1 -uroot -ppassword -e "SET GLOBAL FOREIGN_KEY_CHECKS=1;"
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: laravel
        DB_USERNAME: root
        DB_PASSWORD: password

    - name: Execute tests via PHPUnit
      run: vendor/bin/phpunit
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: laravel
        DB_USERNAME: root
        DB_PASSWORD: password
